import pyautogui
from time import sleep

pyautogui.moveTo(87,1059)
sleep(0.5)
pyautogui.click()
pyautogui.write("chrome")
pyautogui.moveTo(128,519)
sleep(0.5)
pyautogui.click()
sleep(0.5)
pyautogui.write("www.instagram.com")
pyautogui.press("enter")
sleep(5)
pyautogui.moveTo(995,301)
pyautogui.click()
pyautogui.write("bela_flor_gi")
pyautogui.press("enter")
sleep(3)
pyautogui.moveTo(1174,292)
pyautogui.click()
sleep(1)
pyautogui.moveTo(1799,732)
pyautogui.click()
sleep(1)
pyautogui.moveTo(1493,921)
pyautogui.click()
sleep(0.5)
pyautogui.moveTo(1498,918)
pyautogui.click()
pyautogui.write("Muito amor envolvido!!!")
pyautogui.press("enter")
